dev: &dev
  datadir: C:/Users/niedo/Documents/roehl_app_catalog_test_data/dockhours
  dbdir: db
development: *dev

test: &test
  datadir: C:/Users/niedo/Documents/roehl_app_catalog_test_data/dockhours
  dbdir: db
