dev: &dev
  dbdir: db
  datadir: //pc1932/c$/Users/niedo/Documents/roehl_app_catalog_test_data
  buildmanagerdir: //pc1932/c$/Users/niedo/Documents/roehl_app_catalog_test_data
  branchdir: //pc1932/c$/Users/niedo/Documents/roehl_app_catalog_test_data
  taskssubdir: c$/Users/niedo/Documents/roehl_app_catalog_test_data/services_and_tasks/tasks

development: *dev

test: &test
  dbdir: db
  datadir: //pc1932/c$/Users/niedo/Documents/roehl_app_catalog_test_data
  buildmanagerdir: //pc1932/c$/code/branches/niedo2/shared/windowapps/buildmanager/data
  branchdir: //pc1932/c$/code/branches/niedo2
  taskssubdir: c$/Users/niedo/Documents/roehl_app_catalog_test_data/services_and_tasks/tasks
